### ISSUE TITLE
Breaking no entry flag

### ISSUE THREAD

**Issue by srnyx** [drbot7/GriefPreventionFlags#11]
When a player that isn't allowed in a claim tries to fly (with an Elytra) into the claim, they get stuck in the air.
Then, when they leave/rejoin, they are put inside of the claim, bypassing the no entry flag.

**Comment by drbot7** [comment]
I've pushed some changes. Let me know if this fixes it please! https://cdn.discordapp.com/attachments/751679912246771722/920172853385650226/GriefPreventionFlags-5.11.3-SNAPSHOT.jar
