### ISSUE TITLE
Allowpvp doesn't work

### ISSUE THREAD

**Issue by Bartek200219** [drbot7/GriefPreventionFlags#12]
When pvp protection is disabled in GriefPrevention config when allowpvp value is set to false, people still can fight.
When pvp protection is enabled in GriefPrevention config when allowpvp value is set to true, people still can't fight.
Either way I think it's a bug
GriefPrevention 16.17.1-33-g6debf36
GriefPreventionFlags 5.11.2
Paper 1.18-22

**Comment by Bartek200219** [comment]
Testing further, nofiredamage doesn't work too.
`'5':
  nofiredamage:
    params: ''
    value: true
everywhere:
  nofiredamage:
    params: ''
    value: true
`This is what I found in flags.yml and still even after restart players get damaged by fire.

**Comment by drbot7** [comment]
For the issue about allowpvp, disable pvp protection in the GriefPrevention config, and enable PvP Only In PvP-Flagged Claims in the gpflags config.

For the issue about fire damage, nofiredamage relates to fire damaging blocks. It doesn't actually protect players.
