### ISSUE TITLE
Entrance to claim when there is noentry flag

### ISSUE THREAD

**Issue by SirvydasS** [drbot7/GriefPreventionFlags#16]
**Describe the bug**

**To Reproduce**
1. Fly fast with fireworks to claim where you are denied to enter, non stop. 
2. Disconect from server adn rejoin.
3. You can freely walk in the claim.

**Expected behavior**
Can't use this bug and You should not able move in claim.

**Screenshots or Videos**
https://youtu.be/SWwZI3ptB1A

**Versions:**
 - GriefPrevention version 16.18-RC1-1-g06cc566
 - GPFlags version GriefPreventionFlags version 5.11.2
 - Server version  Paper version git-Paper-198 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: c50fc3a)

**Comment by drbot7** [comment]
This has already been fixed. See https://github.com/drbot7/GriefPreventionFlags/issues/11
