### ISSUE TITLE
[Suggestion] Allow Shorthand Format Hex Codes In Enter/Exit Messages

### ISSUE THREAD

**Issue by WhatsTheBadNews** [drbot7/GriefPreventionFlags#6]

**Comment by drbot7** [comment]
So it looks like the plugin already supports shorthand hex colors. The format is a little different than what I'm used to though. It uses `<#rrggbb>` instead of `&#rrggbb`. I do still want to add support for the latter format. It's just not as high on my priority list.

**Comment by drbot7** [comment]
I've pushed some changes for this now to the main branch. You can download a dev build from the birdflop discord, or wait a little bit and I'll probably upload a release to the Spigot page soon
